# made by @DneZyeK


from time import sleep
from userbot.events import register


@register(outgoing=True, pattern='^.senator(?: |$)(.*)')
async def typewriter(typew):
    await typew.edit("`ПОЖАЛУЙСТА ПРОЧТИ ДО КОНЦА🖤`")
    sleep(1)
    await typew.edit("...")
    await typew.edit(str(number) + "   Я")
    sleep(1)
    await typew.edit(str(number) + "   хочу")
    sleep(1)
    await typew.edit(str(number) + "   тебе")
    sleep(1)
    await typew.edit(str(number) + "   сказать")
    sleep(1)
    await typew.edit(str(number) + "   что")
    sleep(1)
    await typew.edit(str(number) + "   ты")
    sleep(1)
    await typew.edit(str(number) + "   самая")
    sleep(1)
    await typew.edit(str(number) + "   лучшая")
    sleep(1)
    await typew.edit(str(number) + "   ты")
    sleep(1)
    await typew.edit(str(number) + "   самая")
    sleep(1)
    await typew.edit(str(number) + "   прекрасная")
    sleep(1)
    await typew.edit(str(number) + "   доборая")
    sleep(1)
    await typew.edit(str(number) + "   хорошая")
    sleep(1)
    await typew.edit(str(number) + "   красивая")
    sleep(1)
    await typew.edit(str(number) + "   улыбнись")
    sleep(1)
    await typew.edit(str(number) + "   ведь")
    sleep(1)
    await typew.edit(str(number) + "   тебе идет")
    sleep(1)
    await typew.edit(str(number) + "   улыбка")
    sleep(1)
    await typew.edit(str(number) + "   и")
    sleep(1)
    await typew.edit(str(number) + "   кто-бы")
    sleep(1)
    await typew.edit(str(number) + "   чтобы")
    sleep(1)
    await typew.edit(str(number) + "   не говорил")
    sleep(1)
    await typew.edit(str(number) + "   знай")
    sleep(1)
    await typew.edit(str(number) + "    ты самая")
    sleep(1)
    await typew.edit(str(number) + "   прекрасная")
    sleep(1)
    await typew.edit(str(number) + "   в этом мире")
    sleep(1)
    await typew.edit(str(number) + "   ♥️😘❤️")
    sleep(1)
    await typew.edit(str(number) + "   С ЛЮБОВЬ")
    
    sleep(1)
    await typew.edit("`SENATOR`")
